recipes:
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_set_magnification_on
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_show_path_bar
        - osxdefaults::finder_show_status_bar
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_unhide_home
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::tap_to_click
attributes:
    homebrewalt:
        apps:
            - imagemagick
        cask_apps:
            - firefox
            - flash-player
            - gimp
            - java
            - google-chrome
            - skype
            - sonos
            - vlc
